version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: main
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: main
    groups:
      all-devcontainers:
        patterns:
          - "*"
