[project]
    name            = "daily-realtor"
    version         = "0.1.0"
    description     = "Daily property listings for my mom"
    readme          = "README.md"
    requires-python = ">=3.13"
    dependencies    = ["pydantic==2.11.5", "requests==2.32.3"]

[tool.uv]
    package = false
